services:
  ubuntu-ssh:
    image: ubuntu:22.04
    container_name: ubuntu-ssh
    ports:
      - "2222:22"
    command: >
      bash -c "
        apt update &&
        apt install -y openssh-server sudo &&
        useradd -m devuser && echo 'devuser:1234' | chpasswd &&
        mkdir -p /var/run/sshd &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        /usr/sbin/sshd -D
      "

