version: '3.8'

services:
  ubuntu-service:
    image: ubuntu:22.04
    container_name: ubuntu-service
    restart: unless-stopped
    command: >
      bash -c "\
        apt-get update -y && apt-get install -y openssh-server sudo curl vim && \
        useradd -m devuser && echo 'devuser:1234' | chpasswd && \
        mkdir -p /var/run/sshd && /usr/sbin/sshd -D"
    # If you want to connect from outside for admin/debug, uncomment the port mapping below
    # ports:
    #   - "2222:22"
    networks:
      - prod-network

  backend:
    build: .
    container_name: nest-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TARGET_HOST=ubuntu-service
      - TARGET_PORT=22
      - TARGET_USER=devuser
      - TARGET_PASS=1234
      # Optional tuning for SSH connect retries/backoff
      - SSH_CONNECT_RETRIES=5
      - SSH_CONNECT_BACKOFF_MS=500
    depends_on:
      - ubuntu-service
    networks:
      - prod-network

networks:
  prod-network:
    driver: bridge

volumes: {}
