-- MySQL Script generated by MySQL Workbench
-- Sun Sep 28 19:53:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) NULL,
  `correo` VARCHAR(60) NULL,
  `contraseña` VARCHAR(45) NULL,
  `avatar` INT NULL,
  `racha` INT NULL,
  `experiencia` INT NULL,
  PRIMARY KEY (`id_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lecciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Lecciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Lecciones` (
  `id_Leccion` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Leccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Progresos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Progresos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Progresos` (
  `Usuarios_id_Usuario` INT NOT NULL,
  `Lecciones_id_Leccion` INT NOT NULL,
  `progreso` INT NULL,
  PRIMARY KEY (`Usuarios_id_Usuario`, `Lecciones_id_Leccion`),
  INDEX `fk_Progresos_Lecciones1_idx` (`Lecciones_id_Leccion` ASC) VISIBLE,
  CONSTRAINT `fk_Progresos_Usuarios`
    FOREIGN KEY (`Usuarios_id_Usuario`)
    REFERENCES `mydb`.`Usuarios` (`id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Progresos_Lecciones1`
    FOREIGN KEY (`Lecciones_id_Leccion`)
    REFERENCES `mydb`.`Lecciones` (`id_Leccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Retos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Retos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Retos` (
  `id_Reto` INT NOT NULL,
  `descripcion` VARCHAR(300) NULL,
  `Retroalimentacion` VARCHAR(150) NULL,
  `Lecciones_id_Leccion` INT NOT NULL,
  PRIMARY KEY (`id_Reto`, `Lecciones_id_Leccion`),
  INDEX `fk_Retos_Lecciones1_idx` (`Lecciones_id_Leccion` ASC) VISIBLE,
  CONSTRAINT `fk_Retos_Lecciones1`
    FOREIGN KEY (`Lecciones_id_Leccion`)
    REFERENCES `mydb`.`Lecciones` (`id_Leccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comandos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comandos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comandos` (
  `id_Comando` INT NOT NULL AUTO_INCREMENT,
  `comando` VARCHAR(45) NULL,
  `Retos_id_Reto` INT NOT NULL,
  `Retos_Lecciones_id_Leccion` INT NOT NULL,
  PRIMARY KEY (`id_Comando`, `Retos_id_Reto`, `Retos_Lecciones_id_Leccion`),
  INDEX `fk_Comandos_Retos1_idx` (`Retos_id_Reto` ASC, `Retos_Lecciones_id_Leccion` ASC) VISIBLE,
  CONSTRAINT `fk_Comandos_Retos1`
    FOREIGN KEY (`Retos_id_Reto` , `Retos_Lecciones_id_Leccion`)
    REFERENCES `mydb`.`Retos` (`id_Reto` , `Lecciones_id_Leccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
